#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
	addgroup --system --quiet tcollector || true
	adduser --system --quiet --ingroup tcollector --no-create-home --home /var/lib/tcollector tcollector || true
fi

#DEBHELPER#
